#!/usr/bin/env bash

if [[ -z $RUNNER_TEMP ]]; then
  RUNNER_TEMP=$(git rev-parse --show-toplevel)
fi

# First, insert docc-plugin dependency. This is very hacky, but it avoids everyone having to pull in the docc-plugin when they use this library.
DEPENDENCY_LINE='.package(url: "https://github.com/apple/swift-docc-plugin", branch: "main"),'
# sed -i '/dependencies/a \n' "$RUNNER_TEMP/Package.swift"

mv "$RUNNER_TEMP/Package.swift" "$RUNNER_TEMP/Package.swift.tmp"

sed '/swift-http-types.git/a\
.package(url: "https://github.com/apple/swift-docc-plugin", branch: "main"),' "$RUNNER_TEMP/Package.swift.tmp" > "$RUNNER_TEMP/Package.swift"

swift package \
  --allow-writing-to-directory "$RUNNER_TEMP/docs" \
  generate-documentation \
  --target HPNetwork \
  --transform-for-static-hosting \
  --hosting-base-path HPNetwork \
  --output-path "$RUNNER_TEMP/docs"

echo "<script>window.location.href += \"documentation/hpnetwork\"</script>" > "$RUNNER_TEMP/docs/index.html"

rm "$RUNNER_TEMP/Package.swift"
mv "$RUNNER_TEMP/Package.swift.tmp" "$RUNNER_TEMP/Package.swift"